#line 1 "lexer.flex.cpp"

#line 3 "lexer.flex.cpp"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

#define YY_FLEX_LEX_COMPAT
extern int yylineno;
int yylineno = 1;

extern char yytext[];

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	if ( yyleng >= YYLMAX ) \
		YY_FATAL_ERROR( "token too large, exceeds YYLMAX" ); \
	yy_flex_strncpy( yytext, (yytext_ptr), yyleng + 1 ); \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 122
#define YY_END_OF_BUFFER 123
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[398] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
      123,  122,  121,   83,   70,   94,  100,  101,   78,   72,
      105,   75,  106,   90,  114,  122,  104,  107,   88,   80,
       86,   69,  120,   98,   99,   92,  120,  120,  120,  120,
      120,  120,  120,  120,  120,  120,  120,  108,  120,  120,
      120,  120,  120,  120,  120,  120,  102,   96,  103,   93,
      110,  122,  121,   84,   71,   95,   79,   74,   73,   77,
       76,  109,  113,   91,    0,    0,    0,    0,  116,    0,
       89,   81,   87,  120,  120,  120,    3,  120,  120,  120,
      120,  120,  120,   16,  120,  120,  120,  120,  120,  120,

      120,  120,  120,   27,  120,   30,   34,  120,  120,  120,
      120,  120,  120,  120,   44,  120,  120,  120,  120,  120,
      120,  120,  120,  120,  120,  120,  120,  120,  120,  120,
       97,  110,  111,    0,  112,   85,  113,  117,    0,  115,
      118,  119,  114,  116,    0,    0,   82,  120,    2,  120,
      120,  120,  120,  120,  120,  120,  120,  120,  120,  120,
      120,  120,  120,  120,  120,   23,  120,  120,   26,  120,
      120,  120,  120,  120,   36,  120,  120,  120,   40,  120,
      120,  120,  120,  120,  120,  120,  120,  120,  120,   52,
      120,  120,  120,  120,  120,  120,  120,  120,   61,  120,

      120,  120,  120,   66,  120,  117,    0,  115,    0,  118,
        0,  119,    0,    0,    0,  114,  120,  120,  120,    6,
      120,  120,  120,  120,  120,  120,  120,  120,   17,   18,
      120,  120,  120,  120,   24,  120,  120,  120,  120,  120,
      120,  120,  120,  120,  120,   41,  120,  120,  120,  120,
      120,  120,  120,  120,  120,  120,  120,  120,  120,  120,
       58,  120,   60,   62,  120,  120,  120,  120,    0,    0,
      114,    0,  120,  120,    5,    7,    8,   10,  120,  120,
      120,  120,  120,  120,  120,   21,  120,  120,  120,  120,
       31,  120,  120,   35,  120,  120,   39,  120,  120,  120,

      120,  120,  120,  120,  120,  120,  120,  120,   55,  120,
      120,   59,  120,  120,  120,  120,   67,  120,  120,  120,
      120,  120,  120,  120,   15,   19,  120,  120,  120,  120,
       29,  120,  120,   37,  120,   42,   43,  120,  120,  120,
       48,  120,  120,   51,   53,   54,   56,   57,   63,  120,
       64,  120,  120,    4,  120,  120,  120,   13,   14,   20,
       22,  120,  120,  120,  120,  120,   45,   46,  120,  120,
       50,  120,   65,    1,  120,    9,   12,   25,  120,  120,
      120,  120,  120,   49,  120,  120,  120,  120,   33,   38,
       47,   68,  120,   28,   32,   11,    0

    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        2,    2,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    1,    1,    1,    5,    6,    1,    7,
        8,    9,   10,   11,   12,   13,   14,   15,   16,   17,
       17,   17,   17,   17,   17,   18,   18,   19,   20,   21,
       22,   23,   24,    1,   25,   26,   25,   25,   27,   25,
       28,   28,   28,   28,   28,   28,   28,   28,   29,   28,
       28,   28,   28,   28,   28,   28,   28,   30,   28,   28,
       31,    1,   32,   33,   34,    1,   35,   36,   37,   38,

       39,   40,   41,   42,   43,   44,   45,   46,   47,   48,
       49,   50,   51,   52,   53,   54,   55,   56,   57,   58,
       59,   28,   60,   61,   62,   63,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[64] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    3,    1,
        1,    1,    1,    1,    4,    4,    4,    4,    1,    1,
        1,    1,    1,    1,    4,    4,    4,    5,    5,    5,
        1,    1,    1,    6,    4,    4,    4,    4,    4,    4,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    1,
        1,    1,    1
    } ;

static const flex_int16_t yy_base[406] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,  534,  533,
      541,  544,   62,  518,  517,  532,  544,  544,  515,   56,
      544,   55,  544,   59,   53,   54,  544,  544,  514,  513,
      512,  544,    0,  544,  544,  544,   38,   35,   50,   51,
       47,   63,  494,   61,  493,  492,  481,   68,   77,   69,
      490,   71,   77,  480,  492,  484,  544,  464,  544,  544,
        0,  113,   73,  502,  544,  544,  544,  544,  544,  544,
      544,  544,    0,  544,  116,  123,  127,    0,  132,  136,
      544,  501,  544,    0,  469,  462,    0,  471,  480,  102,
      483,  469,  121,    0,  463,  460,   66,  468,  465,  460,

      462,  462,  455,    0,  458,  120,    0,  448,  452,  467,
      457,  106,  118,  459,    0,  465,  126,  465,  133,  446,
      137,  449,  455,  450,   94,  121,  446,  140,  443,  451,
      544,    0,  168,  172,  544,  544,    0,  175,  177,  181,
      185,  459,  189,  195,  208,  215,  544,  438,    0,  445,
      455,  450,  451,  434,  182,  431,  439,  449,  444,  443,
      434,  431,  440,  425,  442,    0,  429,  438,    0,   48,
      435,  419,  433,  422,    0,  415,  430,  429,    0,  421,
      430,  426,  419,  407,  408,  415,  422,  404,  403,    0,
      403,  413,  416,  400,  417,  399,  402,  411,    0,  410,

      409,  396,  398,    0,  399,  222,  224,  226,  230,  234,
      237,  410,  409,  246,  254,  259,  390,  402,  395,    0,
      397,  385,  383,  393,  394,  399,  378,  378,    0,    0,
      379,  382,  390,  382,    0,  373,  387,  373,  372,  388,
      370,  381,  374,  366,  366,    0,  378,  379,  380,  379,
      374,  369,  362,  367,  357,  365,  359,  354,  368,  355,
        0,  346,    0,  353,  361,  345,  350,  359,  271,  266,
      279,  284,  362,  361,    0,    0,    0,  343,  346,  352,
      340,  345,  351,  335,  350,    0,  341,  343,  338,  330,
        0,  335,  342,    0,  342,  330,    0,  327,  324,  336,

      322,  338,  337,  325,  320,  323,  333,  328,    0,  326,
      321,    0,  326,  322,  325,  306,    0,  325,  313,  305,
      304,  319,  318,  302,    0,    0,  302,  295,  304,  313,
        0,  314,  315,    0,  313,    0,    0,  303,  292,  258,
        0,  265,  270,    0,    0,    0,    0,    0,    0,  260,
        0,  259,  252,    0,  267,  264,  240,    0,    0,    0,
        0,  243,  242,  240,  241,  230,    0,    0,  227,  206,
        0,  220,    0,    0,  204,    0,    0,    0,  203,  206,
      188,  182,  179,    0,  176,  154,  135,  139,    0,    0,
        0,    0,  118,    0,    0,    0,  544,  313,  319,  322,

      328,  334,  340,  130,  343
    } ;

static const flex_int16_t yy_def[406] =
    {   0,
      397,    1,  398,  398,  398,  398,  398,  398,  399,  399,
      397,  397,  397,  397,  397,  397,  397,  397,  397,  397,
      397,  397,  397,  397,  397,  397,  397,  397,  397,  397,
      397,  397,  400,  397,  397,  397,  400,  400,  400,  400,
      400,  400,  400,  400,  400,  400,  400,  400,  400,  400,
      400,  400,  400,  400,  400,  400,  397,  397,  397,  397,
      401,  402,  397,  397,  397,  397,  397,  397,  397,  397,
      397,  397,  403,  397,  397,  397,  397,  404,  397,  397,
      397,  397,  397,  400,  400,  400,  400,  400,  400,  400,
      400,  400,  400,  400,  400,  400,  400,  400,  400,  400,

      400,  400,  400,  400,  400,  400,  400,  400,  400,  400,
      400,  400,  400,  400,  400,  400,  400,  400,  400,  400,
      400,  400,  400,  400,  400,  400,  400,  400,  400,  400,
      397,  401,  402,  402,  397,  397,  403,  397,  397,  397,
      397,  405,  397,  397,  397,  397,  397,  400,  400,  400,
      400,  400,  400,  400,  400,  400,  400,  400,  400,  400,
      400,  400,  400,  400,  400,  400,  400,  400,  400,  400,
      400,  400,  400,  400,  400,  400,  400,  400,  400,  400,
      400,  400,  400,  400,  400,  400,  400,  400,  400,  400,
      400,  400,  400,  400,  400,  400,  400,  400,  400,  400,

      400,  400,  400,  400,  400,  397,  397,  397,  397,  397,
      397,  405,  405,  397,  397,  397,  400,  400,  400,  400,
      400,  400,  400,  400,  400,  400,  400,  400,  400,  400,
      400,  400,  400,  400,  400,  400,  400,  400,  400,  400,
      400,  400,  400,  400,  400,  400,  400,  400,  400,  400,
      400,  400,  400,  400,  400,  400,  400,  400,  400,  400,
      400,  400,  400,  400,  400,  400,  400,  400,  397,  397,
      397,  397,  400,  400,  400,  400,  400,  400,  400,  400,
      400,  400,  400,  400,  400,  400,  400,  400,  400,  400,
      400,  400,  400,  400,  400,  400,  400,  400,  400,  400,

      400,  400,  400,  400,  400,  400,  400,  400,  400,  400,
      400,  400,  400,  400,  400,  400,  400,  400,  400,  400,
      400,  400,  400,  400,  400,  400,  400,  400,  400,  400,
      400,  400,  400,  400,  400,  400,  400,  400,  400,  400,
      400,  400,  400,  400,  400,  400,  400,  400,  400,  400,
      400,  400,  400,  400,  400,  400,  400,  400,  400,  400,
      400,  400,  400,  400,  400,  400,  400,  400,  400,  400,
      400,  400,  400,  400,  400,  400,  400,  400,  400,  400,
      400,  400,  400,  400,  400,  400,  400,  400,  400,  400,
      400,  400,  400,  400,  400,  400,    0,  397,  397,  397,

      397,  397,  397,  397,  397
    } ;

static const flex_int16_t yy_nxt[608] =
    {   0,
       12,   13,   13,   14,   15,   16,   17,   18,   19,   20,
       21,   22,   23,   24,   25,   26,   26,   26,   27,   28,
       29,   30,   31,   32,   33,   33,   33,   33,   33,   33,
       34,   35,   36,   33,   37,   38,   39,   40,   41,   42,
       43,   33,   44,   33,   45,   46,   47,   48,   49,   50,
       33,   51,   52,   53,   54,   55,   56,   33,   33,   57,
       58,   59,   60,   63,   63,   68,   70,   72,   79,   79,
       79,   79,   73,   85,   63,   63,   71,   69,   75,   76,
       74,   77,   78,   88,   90,   86,   89,   80,   75,   93,
       87,   76,   95,  237,   96,   91,  238,   98,   92,   94,

      104,   77,  111,  116,   97,   99,  112,  105,  106,  120,
       78,  100,  114,  107,  101,  162,  115,  102,  125,  163,
      117,  134,  113,  118,  121,  122,  135,  123,  126,  124,
      138,  138,  139,  142,  139,  127,  196,  140,  140,  140,
      140,  141,  141,  141,  143,  197,  144,  144,  144,  144,
       79,   79,   79,   79,  152,  153,  156,  157,  145,  171,
      158,  178,  179,  180,  181,  146,  159,  187,  184,  396,
      145,  191,  172,  173,  185,  198,  397,  201,  395,  199,
      134,  397,  202,  188,  203,  135,  189,  394,  192,  206,
      206,  140,  140,  140,  140,  208,  208,  208,  208,  210,

      210,  210,  393,  214,  214,  214,  214,  143,  207,  144,
      144,  144,  144,  392,  209,  145,  391,  215,  211,  215,
      390,  145,  216,  216,  216,  216,  389,  145,  146,  144,
      144,  144,  144,  145,  223,  224,  206,  206,  206,  206,
      208,  208,  208,  208,  208,  208,  208,  208,  210,  210,
      210,  210,  210,  210,  388,  207,  387,  386,  385,  209,
      269,  269,  269,  269,  384,  383,  382,  211,  216,  216,
      216,  216,   76,  271,  271,  271,  271,  381,  380,  270,
      269,  269,  269,  269,   76,  269,  269,  269,  269,  379,
      378,  377,  272,  271,  271,  271,  271,   76,  271,  271,

      271,  271,  376,  375,  270,  374,  373,  372,  371,   76,
      370,  369,  272,   12,   12,   12,   12,   12,   12,   61,
       61,   61,   61,   61,   61,   84,   84,   84,  132,  132,
      368,  132,  132,  132,  133,  133,  133,  133,  133,  133,
      137,  367,  137,  137,  137,  137,  212,  366,  212,  365,
      364,  363,  362,  361,  360,  359,  358,  357,  356,  355,
      354,  353,  352,  351,  350,  349,  348,  347,  346,  345,
      344,  343,  342,  341,  340,  339,  338,  337,  336,  335,
      334,  333,  332,  331,  330,  329,  328,  327,  326,  325,
      324,  323,  322,  321,  320,  319,  318,  317,  316,  315,

      314,  313,  312,  311,  310,  309,  308,  307,  306,  305,
      304,  303,  302,  301,  300,  299,  298,  297,  296,  295,
      294,  293,  292,  291,  290,  289,  288,  287,  286,  285,
      284,  283,  282,  281,  280,  279,  278,  277,  276,  275,
      274,  273,  397,  213,  268,  267,  266,  265,  264,  263,
      262,  261,  260,  259,  258,  257,  256,  255,  254,  253,
      252,  251,  250,  249,  248,  247,  246,  245,  244,  243,
      242,  241,  240,  239,  236,  235,  234,  233,  232,  231,
      230,  229,  228,  227,  226,  225,  222,  221,  220,  219,
      218,  217,  213,  205,  204,  200,  195,  194,  193,  190,

      186,  183,  182,  177,  176,  175,  174,  170,  169,  168,
      167,  166,  165,  164,  161,  160,  155,  154,  151,  150,
      149,  148,  147,  136,  131,  130,  129,  128,  119,  110,
      109,  108,  103,   83,   82,   81,   67,   66,   65,   64,
      397,   62,   62,   11,  397,  397,  397,  397,  397,  397,
      397,  397,  397,  397,  397,  397,  397,  397,  397,  397,
      397,  397,  397,  397,  397,  397,  397,  397,  397,  397,
      397,  397,  397,  397,  397,  397,  397,  397,  397,  397,
      397,  397,  397,  397,  397,  397,  397,  397,  397,  397,
      397,  397,  397,  397,  397,  397,  397,  397,  397,  397,

      397,  397,  397,  397,  397,  397,  397
    } ;

static const flex_int16_t yy_chk[608] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,   13,   13,   20,   22,   24,   26,   26,
       26,   26,   24,   37,   63,   63,   22,   20,   25,   25,
       24,   25,   25,   38,   39,   37,   38,   26,   25,   40,
       37,   25,   41,  170,   41,   39,  170,   42,   39,   40,

       44,   25,   48,   50,   41,   42,   48,   44,   44,   52,
       25,   42,   49,   44,   42,   97,   49,   42,   53,   97,
       50,   62,   48,   50,   52,   52,   62,   52,   53,   52,
       75,   75,   76,  404,   76,   53,  125,   76,   76,   76,
       76,   77,   77,   77,   79,  125,   79,   79,   79,   79,
       80,   80,   80,   80,   90,   90,   93,   93,   79,  106,
       93,  112,  112,  113,  113,   79,   93,  119,  117,  393,
       79,  121,  106,  106,  117,  126,  133,  128,  388,  126,
      134,  133,  128,  119,  128,  134,  119,  387,  121,  138,
      138,  139,  139,  139,  139,  140,  140,  140,  140,  141,

      141,  141,  386,  143,  143,  143,  143,  144,  138,  144,
      144,  144,  144,  385,  140,  143,  383,  145,  141,  145,
      382,  144,  145,  145,  145,  145,  381,  143,  144,  146,
      146,  146,  146,  144,  155,  155,  206,  206,  207,  207,
      208,  208,  208,  208,  209,  209,  209,  209,  210,  210,
      210,  211,  211,  211,  380,  206,  379,  375,  372,  208,
      214,  214,  214,  214,  370,  369,  366,  210,  215,  215,
      215,  215,  214,  216,  216,  216,  216,  365,  364,  214,
      270,  270,  270,  270,  214,  269,  269,  269,  269,  363,
      362,  357,  216,  271,  271,  271,  271,  269,  272,  272,

      272,  272,  356,  355,  269,  353,  352,  350,  343,  269,
      342,  340,  271,  398,  398,  398,  398,  398,  398,  399,
      399,  399,  399,  399,  399,  400,  400,  400,  401,  401,
      339,  401,  401,  401,  402,  402,  402,  402,  402,  402,
      403,  338,  403,  403,  403,  403,  405,  335,  405,  333,
      332,  330,  329,  328,  327,  324,  323,  322,  321,  320,
      319,  318,  316,  315,  314,  313,  311,  310,  308,  307,
      306,  305,  304,  303,  302,  301,  300,  299,  298,  296,
      295,  293,  292,  290,  289,  288,  287,  285,  284,  283,
      282,  281,  280,  279,  278,  274,  273,  268,  267,  266,

      265,  264,  262,  260,  259,  258,  257,  256,  255,  254,
      253,  252,  251,  250,  249,  248,  247,  245,  244,  243,
      242,  241,  240,  239,  238,  237,  236,  234,  233,  232,
      231,  228,  227,  226,  225,  224,  223,  222,  221,  219,
      218,  217,  213,  212,  205,  203,  202,  201,  200,  198,
      197,  196,  195,  194,  193,  192,  191,  189,  188,  187,
      186,  185,  184,  183,  182,  181,  180,  178,  177,  176,
      174,  173,  172,  171,  168,  167,  165,  164,  163,  162,
      161,  160,  159,  158,  157,  156,  154,  153,  152,  151,
      150,  148,  142,  130,  129,  127,  124,  123,  122,  120,

      118,  116,  114,  111,  110,  109,  108,  105,  103,  102,
      101,  100,   99,   98,   96,   95,   92,   91,   89,   88,
       86,   85,   82,   64,   58,   56,   55,   54,   51,   47,
       46,   45,   43,   31,   30,   29,   19,   16,   15,   14,
       11,   10,    9,  397,  397,  397,  397,  397,  397,  397,
      397,  397,  397,  397,  397,  397,  397,  397,  397,  397,
      397,  397,  397,  397,  397,  397,  397,  397,  397,  397,
      397,  397,  397,  397,  397,  397,  397,  397,  397,  397,
      397,  397,  397,  397,  397,  397,  397,  397,  397,  397,
      397,  397,  397,  397,  397,  397,  397,  397,  397,  397,

      397,  397,  397,  397,  397,  397,  397
    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[123] =
    {   0,
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 1, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
#ifndef YYLMAX
#define YYLMAX 8192
#endif

char yytext[YYLMAX];
char *yytext_ptr;
#line 1 "lexer.l"
#line 6 "lexer.l"

#include <string>
#include <algorithm>
#include <charconv>
#include <iostream>
#include <cstdio>


void Print(const std::string& message)
{
    std::cout << message << std::endl;
}

void PrintError(const std::string& errorMessage, const int line = -1) 
{
    std::cerr << "error: " <<errorMessage << std::endl;
    if (line >= 0)
        std::cerr << "error line: " << line << std::endl;
    std::cerr << std::endl;
}

void PrintIntegerLiteral(const std::string& type, const int integer) {
    Print("Found " + type + " integer literal: " + std::to_string(integer));
}

void PrintFloatingPointLiteral(const double floatingPoint) {
    Print("Found floating point literal: " + std::to_string(floatingPoint));
}

void RemoveCharacterFromString(std::string& str, char ch) {
    const auto newLast = std::remove(str.begin(), str.end(), ch);
    str.erase(newLast, str.end());
}

void RemoveUnderline(std::string& str) {
    RemoveCharacterFromString(str, '_');
}

#line 787 "lexer.flex.cpp"

#line 789 "lexer.flex.cpp"

#define INITIAL 0
#define STR_DOUBLE_Q 1
#define STR_SINGLE_Q 2
#define STR_BACK_Q 3
#define MULTILINE_COMMENT 4

/*windows compatibility case*/
#include <io.h>
#define isatty _isatty
#define fileno _fileno
    
#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 71 "lexer.l"




#line 76 "lexer.l"
std::string currentString;
std::string currentComment;

int currentInteger;
char currentCharacter;
double currentFloatingPoint;
char buffer[10];    
char bufferString[1000];



#line 1024 "lexer.flex.cpp"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 398 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_current_state != 397 );
		yy_cp = (yy_last_accepting_cpos);
		yy_current_state = (yy_last_accepting_state);

yy_find_action:
		yy_act = yy_accept[yy_current_state];

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 87 "lexer.l"
{ Print("Found KW_ABSTRACT: " + std::string{yytext}); } 
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 88 "lexer.l"
{ Print("Found TYPE_ANY: " + std::string{yytext}); } 
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 89 "lexer.l"
{ Print("Found KW_AS: " + std::string{yytext}); } 
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 90 "lexer.l"
{ Print("Found TYPE_BOOLEAN: " + std::string{yytext}); } 
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 91 "lexer.l"
{ Print("Found KW_BREAK: " + std::string{yytext}); } 
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 92 "lexer.l"
{ Print("Found KW_CASE: " + std::string{yytext}); } 
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 93 "lexer.l"
{ Print("Found KW_CATCH: " + std::string{yytext}); } 
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 94 "lexer.l"
{ Print("Found KW_CLASS: " + std::string{yytext}); } 
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 95 "lexer.l"
{ Print("Found KW_CONTINUE: " + std::string{yytext}); } 
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 96 "lexer.l"
{ Print("Found KW_CONST: " + std::string{yytext}); } 
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 97 "lexer.l"
{ Print("Found KW_CONSTRUCTOR: " + std::string{yytext}); } 
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 98 "lexer.l"
{ Print("Found KW_DEBUGGER: " + std::string{yytext}); } 
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 99 "lexer.l"
{ Print("Found KW_DECLARE: " + std::string{yytext}); } 
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 100 "lexer.l"
{ Print("Found KW_DEFAULT: " + std::string{yytext}); } 
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 101 "lexer.l"
{ Print("Found KW_DELETE: " + std::string{yytext}); } 
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 102 "lexer.l"
{ Print("Found KW_DO: " + std::string{yytext}); } 
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 103 "lexer.l"
{ Print("Found KW_ELSE: " + std::string{yytext}); } 
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 104 "lexer.l"
{ Print("Found KW_ENUM: " + std::string{yytext}); } 
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 105 "lexer.l"
{ Print("Found KW_EXPORT: " + std::string{yytext}); } 
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 106 "lexer.l"
{ Print("Found KW_EXTENDS: " + std::string{yytext}); } 
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 107 "lexer.l"
{ Print("Found KW_FALSE: " + std::string{yytext}); } 
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 108 "lexer.l"
{ Print("Found KW_FINALLY: " + std::string{yytext}); } 
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 109 "lexer.l"
{ Print("Found KW_FOR: " + std::string{yytext}); } 
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 110 "lexer.l"
{ Print("Found KW_FROM: " + std::string{yytext}); } 
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 111 "lexer.l"
{ Print("Found KW_FUNCTION: " + std::string{yytext}); } 
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 112 "lexer.l"
{ Print("Found KW_GET: " + std::string{yytext}); } 
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 113 "lexer.l"
{ Print("Found KW_IF: " + std::string{yytext}); } 
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 114 "lexer.l"
{ Print("Found KW_IMPLEMENTS: " + std::string{yytext}); } 
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 115 "lexer.l"
{ Print("Found KW_IMPORT: " + std::string{yytext}); } 
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 116 "lexer.l"
{ Print("Found KW_IN: " + std::string{yytext}); } 
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 117 "lexer.l"
{ Print("Found KW_INFER: " + std::string{yytext}); } 
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 118 "lexer.l"
{ Print("Found KW_INSTANCEOF: " + std::string{yytext}); } 
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 119 "lexer.l"
{ Print("Found KW_INTARFACE: " + std::string{yytext}); } 
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 120 "lexer.l"
{ Print("Found KW_IS: " + std::string{yytext}); } 
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 121 "lexer.l"
{ Print("Found KW_KEYOF: " + std::string{yytext}); } 
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 122 "lexer.l"
{ Print("Found KW_LET: " + std::string{yytext}); } 
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 123 "lexer.l"
{ Print("Found KW_MODULE: " + std::string{yytext}); } 
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 124 "lexer.l"
{ Print("Found KW_NAMESPACE: " + std::string{yytext}); } 
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 125 "lexer.l"
{ Print("Found TYPE_NEVER: " + std::string{yytext}); } 
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 126 "lexer.l"
{ Print("Found KW_NEW: " + std::string{yytext}); } 
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 127 "lexer.l"
{ Print("Found KW_NULL: " + std::string{yytext}); } 
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 128 "lexer.l"
{ Print("Found TYPE_NUMBER: " + std::string{yytext}); } 
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 129 "lexer.l"
{ Print("Found TYPE_OBJECT: " + std::string{yytext}); } 
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 130 "lexer.l"
{ Print("Found KW_OF: " + std::string{yytext}); } 
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 131 "lexer.l"
{ Print("Found KW_PACKAGE: " + std::string{yytext}); } 
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 132 "lexer.l"
{ Print("Found KW_PRIVATE: " + std::string{yytext}); } 
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 133 "lexer.l"
{ Print("Found KW_PROTECTED: " + std::string{yytext}); } 
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 134 "lexer.l"
{ Print("Found KW_PUBLIC: " + std::string{yytext}); } 
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 135 "lexer.l"
{ Print("Found KW_READONLY: " + std::string{yytext}); } 
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 136 "lexer.l"
{ Print("Found KW_REQUIRE: " + std::string{yytext}); } 
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 137 "lexer.l"
{ Print("Found KW_RETURN: " + std::string{yytext}); } 
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 138 "lexer.l"
{ Print("Found KW_SET: " + std::string{yytext}); } 
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 139 "lexer.l"
{ Print("Found KW_STATIC: " + std::string{yytext}); } 
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 140 "lexer.l"
{ Print("Found TYPE_STRING: " + std::string{yytext}); } 
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 141 "lexer.l"
{ Print("Found KW_SUPER: " + std::string{yytext}); } 
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 142 "lexer.l"
{ Print("Found KW_SWITCH: " + std::string{yytext}); }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 143 "lexer.l"
{ Print("Found TYPE_SYMBOL: " + std::string{yytext}); }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 144 "lexer.l"
{ Print("Found KW_THIS: " + std::string{yytext}); }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 145 "lexer.l"
{ Print("Found KW_THROW: " + std::string{yytext}); }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 146 "lexer.l"
{ Print("Found KW_TRUE: " + std::string{yytext}); }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 147 "lexer.l"
{ Print("Found KW_TRY: " + std::string{yytext}); }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 148 "lexer.l"
{ Print("Found KW_TYPE: " + std::string{yytext}); }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 149 "lexer.l"
{ Print("Found KW_TYPEOF: " + std::string{yytext}); }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 150 "lexer.l"
{ Print("Found KW_UNIQUE: " + std::string{yytext}); } 
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 151 "lexer.l"
{ Print("Found TYPE_UNKNOWN: " + std::string{yytext}); } 
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 152 "lexer.l"
{ Print("Found KW_VAR: " + std::string{yytext}); }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 153 "lexer.l"
{ Print("Found KW_WHILE: " + std::string{yytext}); }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 154 "lexer.l"
{ Print("Found KW_UNDEFINED: " + std::string{yytext}); }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 156 "lexer.l"
{ Print("Found OPERATOR_OPT_PARAM: " + std::string{yytext}); }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 157 "lexer.l"
{ Print("Found OPERATOR_MOD: " + std::string{yytext}); }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 158 "lexer.l"
{ Print("Found OPERATOR_MOD_ASSIGNMENT: " + std::string{yytext}); }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 159 "lexer.l"
{ Print("Found OPERATOR_PLUS: " + std::string{yytext}); }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 160 "lexer.l"
{ Print("Found OPERATOR_PLUS_ASSIGNMENT: " + std::string{yytext}); }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 161 "lexer.l"
{ Print("Found OPERATOR_INCREMENT: " + std::string{yytext}); }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 162 "lexer.l"
{ Print("Found OPERATOR_MINUS: " + std::string{yytext}); }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 163 "lexer.l"
{ Print("Found OPERATOR_MINUS_ASSIGNMENT: " + std::string{yytext}); }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 164 "lexer.l"
{ Print("Found OPERATOR_DICREMENT: " + std::string{yytext}); }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 165 "lexer.l"
{ Print("Found OPERATOR_MUL: " + std::string{yytext}); }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 166 "lexer.l"
{ Print("Found OPERATOR_MUL_ASSIGNMENT: " + std::string{yytext}); }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 167 "lexer.l"
{ Print("Found OPERATOR_ASSIGNMENT: " + std::string{yytext}); }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 168 "lexer.l"
{ Print("Found OPERATOR_EQUAL: " + std::string{yytext}); }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 169 "lexer.l"
{ Print("Found OPERATOR_EQUAL_BY_TYPE_AND_VALUE: " + std::string{yytext}); }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 170 "lexer.l"
{ Print("Found OPERATOR_BIT_NOT: " + std::string{yytext}); }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 171 "lexer.l"
{ Print("Found OPERATOR_NOT_EQUAL: " + std::string{yytext}); }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 172 "lexer.l"
{ Print("Found OPERATOR_NOT_EQUAL_BY_TYPE_AND_VALUE: " + std::string{yytext}); }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 173 "lexer.l"
{ Print("Found OPERATOR_MORE: " + std::string{yytext}); }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 174 "lexer.l"
{ Print("Found OPERATOR_MORE_OR_EQUAL: " + std::string{yytext}); }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 175 "lexer.l"
{ Print("Found OPERATOR_LESS: " + std::string{yytext}); }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 176 "lexer.l"
{ Print("Found OPERATOR_LESS_OR_EQUA: " + std::string{yytext}); }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 177 "lexer.l"
{ Print("Found OPERATOR_DIV: " + std::string{yytext}); }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 178 "lexer.l"
{ Print("Found OPERATOR_DIV_ASSIGNMENT: " + std::string{yytext}); }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 179 "lexer.l"
{ Print("Found OPERATOR_BIT_XOR: " + std::string{yytext}); }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 180 "lexer.l"
{ Print("Found UNARY_BITWISE_NOT: " + std::string{yytext}); }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 181 "lexer.l"
{ Print("Found OPERATOR_AMPERSAND: " + std::string{yytext}); }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 182 "lexer.l"
{ Print("Found OPERATOR_AND: " + std::string{yytext}); }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 183 "lexer.l"
{ Print("Found OPERATOR_BIT_OR: " + std::string{yytext}); }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 184 "lexer.l"
{ Print("Found OPERATOR_OR: " + std::string{yytext}); }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 185 "lexer.l"
{ Print("Found LEFT_SQUARE_BRACKET: " + std::string{yytext}); }
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 186 "lexer.l"
{ Print("Found RIGHT_SQUARE_BRACKET: " + std::string{yytext}); }
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 187 "lexer.l"
{ Print("Found LEFT_ROUND_BRACKET: " + std::string{yytext}); }
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 188 "lexer.l"
{ Print("Found RIGHT_ROUND_BRACKET: " + std::string{yytext}); }
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 189 "lexer.l"
{ Print("Found LEFT_FIGURE_BRACKET: " + std::string{yytext}); }
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 190 "lexer.l"
{ Print("Found RIGHT_FIGURE_BRACKET: " + std::string{yytext}); }
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 191 "lexer.l"
{ Print("Found COLON: " + std::string{yytext}); }
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 192 "lexer.l"
{ Print("Found COMMA: " + std::string{yytext}); }
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 193 "lexer.l"
{ Print("Found DOT: " + std::string{yytext}); }
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 194 "lexer.l"
{ Print("Found SEMICOLON: " + std::string{yytext}); }
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 195 "lexer.l"
{ Print("Found OPERATOR_ENTER: \\n" + std::string{yytext}); }
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 198 "lexer.l"
{
    currentComment.clear();
    BEGIN(MULTILINE_COMMENT);
}
	YY_BREAK
case 110:
/* rule 110 can match eol */
YY_RULE_SETUP
#line 202 "lexer.l"
{
    currentComment += yytext;
}
	YY_BREAK
case 111:
/* rule 111 can match eol */
YY_RULE_SETUP
#line 205 "lexer.l"
{
    currentComment += yytext;
}
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 208 "lexer.l"
{
    Print("Found multiline comment: \n" + currentComment);
    BEGIN(INITIAL);
}
	YY_BREAK
case YY_STATE_EOF(MULTILINE_COMMENT):
#line 212 "lexer.l"
{
    PrintError("Expected end of multiline comment but found end of file!", yylineno);
    BEGIN(INITIAL);
}
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 217 "lexer.l"
{ 
    Print("Found single-line comment: " + std::string{yytext + 2}); 
}
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 223 "lexer.l"
{ /* Decimal literal */
    std::string number_string = yytext;
    RemoveCharacterFromString(number_string, '_');
    std::from_chars(number_string.c_str(), number_string.c_str() + number_string.size(), currentFloatingPoint);
    PrintFloatingPointLiteral(currentFloatingPoint);
}
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 230 "lexer.l"
{
    std::string number_string = yytext;
    RemoveCharacterFromString(number_string, '_');
    std::from_chars(number_string.c_str(), number_string.c_str() + number_string.size(), currentFloatingPoint);
    PrintFloatingPointLiteral(currentFloatingPoint);
}
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 237 "lexer.l"
{
    std::string number_string = yytext;
    RemoveCharacterFromString(number_string, '_');
    std::from_chars(number_string.c_str(), number_string.c_str() + number_string.size(), currentInteger);
    PrintIntegerLiteral("decimal", currentInteger); 
}
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 245 "lexer.l"
{ /* Binary integer literal */
    currentInteger = 0;
    std::string number_string = yytext;
    RemoveCharacterFromString(number_string, '_');
    std::from_chars(number_string.c_str() + 2, number_string.c_str() + number_string.size(), currentInteger, 2);
    PrintIntegerLiteral("binary", currentInteger); 
}
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 254 "lexer.l"
{  /* Octal integer literal */
    currentInteger = 0;
    std::string number_string = yytext;
    RemoveCharacterFromString(number_string, '_');
    std::from_chars(number_string.c_str() + 2, number_string.c_str() + number_string.size(), currentInteger, 8);
    PrintIntegerLiteral("octal", currentInteger); 
}
	YY_BREAK
case 119:
YY_RULE_SETUP
#line 263 "lexer.l"
{  /* Hexadecimal integer literal */
    currentInteger = 0;
    std::string number_string = yytext;
    RemoveCharacterFromString(number_string, '_');
    std::from_chars(number_string.c_str() + 2, number_string.c_str() + number_string.size(), currentInteger, 16);
    PrintIntegerLiteral("hexadecimal", currentInteger); 
}
	YY_BREAK
case 120:
YY_RULE_SETUP
#line 272 "lexer.l"
{ Print("Found identifier: " + std::string{yytext}); }
	YY_BREAK
case 121:
/* rule 121 can match eol */
YY_RULE_SETUP
#line 275 "lexer.l"
{ /* ignoring */ }
	YY_BREAK
case 122:
YY_RULE_SETUP
#line 277 "lexer.l"
ECHO;
	YY_BREAK
#line 1752 "lexer.flex.cpp"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(STR_DOUBLE_Q):
case YY_STATE_EOF(STR_SINGLE_Q):
case YY_STATE_EOF(STR_BACK_Q):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_last_accepting_cpos);
				yy_current_state = (yy_last_accepting_state);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 398 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 398 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 397);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 277 "lexer.l"


int main(int argc, char *argv[]) {
    if (argc < 2) {
        Print("Usage: %s <input_file>\n" + std::string{argv[0]});
        return 1;
    }

    FILE *input_file = fopen(argv[1], "r");
    if (!input_file) {
        PrintError("could not open file: " + std::string{argv[1]});
        return 1;
    }
    
	FILE* output_file = fopen("output.txt", "w");
	if (!output_file) {
		PrintError("could not create output file\n");
		fclose(input_file);
		return 1;
	}

    yyin = input_file;
    yyout = output_file;
    yylex();        

	fclose(input_file);
	fclose(output_file);
    return 0;
}

