#line 1 "lexer.flex.cpp"

#line 3 "lexer.flex.cpp"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

#define YY_FLEX_LEX_COMPAT
extern int yylineno;
int yylineno = 1;

extern char yytext[];

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	if ( yyleng >= YYLMAX ) \
		YY_FATAL_ERROR( "token too large, exceeds YYLMAX" ); \
	yy_flex_strncpy( yytext, (yytext_ptr), yyleng + 1 ); \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 149
#define YY_END_OF_BUFFER 150
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[441] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
      150,  149,  148,   84,  110,  147,   71,   95,  129,  101,
      102,   79,   73,  106,   76,  107,   91,  141,  149,  105,
      108,   89,   81,   87,   70,   99,  100,   93,  132,  147,
      147,  147,  147,  147,  147,  147,  147,  147,  147,  147,
      109,  147,  147,  147,  147,  147,  147,  147,  147,  103,
       97,  104,   94,  111,  111,  128,  149,  130,  127,  131,
      133,  149,  135,  137,  149,  148,   85,  147,   72,   96,
       80,   75,   74,   78,   77,    0,  136,  140,   92,    0,
        0,    0,    0,  143,    0,   90,   82,   88,  147,  147,

        3,  147,  147,  147,  147,  147,  147,   16,  147,  147,
      147,  147,  147,  147,  147,  147,  147,   27,  147,   30,
       34,  147,  147,  147,  147,  147,  147,  147,   44,  147,
      147,  147,  147,  147,  147,  147,  147,  147,  147,  147,
      147,  147,  147,  147,  147,   98,  111,  126,  117,  116,
      114,  114,  118,  119,  120,  121,  122,  123,  126,  124,
      126,  130,  133,  134,  137,  138,    0,  139,   86,    0,
        0,  140,  144,    0,  142,  145,  146,  141,  143,    0,
        0,   83,  147,    2,  147,  147,  147,  147,  147,  147,
      147,  147,  147,  147,  147,  147,  147,  147,  147,  147,

       23,  147,  147,   26,  147,  147,  147,  147,  147,   36,
      147,  147,  147,   40,  147,  147,  147,  147,  147,  147,
      147,  147,  147,  147,   52,  147,  147,  147,  147,  147,
      147,  147,  147,   61,  147,  147,  147,  147,   67,  147,
      147,  125,  114,  114,  115,  112,  112,    0,  144,    0,
      142,    0,  145,    0,  146,    0,    0,  141,  147,  147,
      147,    6,  147,  147,  147,  147,  147,  147,  147,  147,
       17,   18,  147,  147,  147,  147,   24,  147,  147,  147,
      147,  147,  147,  147,  147,  147,  147,   41,  147,  147,
      147,  147,  147,  147,  147,  147,  147,  147,  147,  147,

      147,  147,   58,  147,   60,   62,  147,  147,  147,   68,
      147,  114,  113,  141,    0,  147,  147,    5,    7,    8,
       10,  147,  147,  147,  147,  147,  147,  147,   21,  147,
      147,  147,  147,   31,  147,  147,   35,  147,  147,   39,
      147,  147,  147,  147,  147,  147,  147,  147,  147,  147,
      147,   55,  147,  147,   59,  147,  147,  147,  147,   69,
      147,  147,  147,  147,  147,  147,  147,   15,   19,  147,
      147,  147,  147,   29,  147,  147,   37,  147,   42,   43,
      147,  147,  147,   48,  147,  147,   51,   53,   54,   56,
       57,   63,  147,   65,  147,  147,    4,  147,  147,  147,

       13,   14,   20,   22,  147,  147,  147,  147,  147,   45,
       46,  147,  147,   50,  147,   66,    1,  147,    9,   12,
       25,  147,  147,  147,  147,  147,   49,  147,  147,  147,
      147,   33,   38,   47,   64,  147,   28,   32,   11,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    2,    3,    4,
        3,    3,    3,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    5,    6,    7,    1,    8,    9,   10,   11,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   21,   22,
       22,   23,   22,   22,   22,   24,   24,   25,   26,   27,
       28,   29,   30,    1,   31,   32,   33,   34,   35,   36,
       37,   38,   39,   40,   40,   41,   41,   41,   42,   40,
       40,   41,   43,   39,   40,   40,   40,   44,   40,   40,
       45,   46,   47,   48,   49,   50,   51,   52,   53,   54,

       55,   56,   57,   58,   59,   60,   61,   62,   63,   64,
       65,   66,   67,   68,   69,   70,   71,   72,   73,   74,
       75,   40,   76,   77,   78,   79,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[80] =
    {   0,
        1,    1,    1,    2,    1,    1,    3,    1,    1,    1,
        4,    5,    5,    6,    1,    5,    1,    1,    1,    7,
        8,    8,    7,    8,    1,    1,    1,    1,    1,    1,
        9,    8,   10,   11,   12,    8,   13,   14,   15,   16,
       17,   17,   18,   14,    1,   19,    1,    1,   20,   21,
        8,    8,    8,    8,    8,    8,   16,   16,   16,   16,
       16,   16,   16,   16,   16,   16,   16,   16,   16,   16,
       16,   16,   16,   16,   16,   22,    1,   22,    1
    } ;

static const flex_int16_t yy_base[458] =
    {   0,
        0,    0,   76,   85,   97,  137,   35,   36,  919,  918,
      931,  934,   90,  902,  934,    0,  901,  918,  934,  934,
      934,  899,   69,  934,   70,   82,   95,  115,  170,  934,
      934,  898,  897,  896,  934,  934,  934,  934,  934,  113,
       23,   48,   35,   71,  136,  868,  142,  867,  866,  855,
       89,   97,  113,  864,  147,  141,  854,   86,  859,  934,
      839,  934,  934,    0,    0,  934,  221,    0,    0,  934,
        0,  865,  934,    0,  152,  226,  886,    0,  934,  934,
      934,  934,  934,  934,  934,  213,  934,    0,  934,  109,
      232,  237,    0,  276,  258,  934,  885,  934,  843,  836,

        0,  845,  854,   86,  857,  843,  213,    0,  837,  834,
       92,  842,  839,  834,  836,  836,  829,    0,  832,  170,
        0,  822,  826,  841,  831,  124,  188,  833,    0,  839,
      149,  839,  118,  820,  159,  823,  829,  824,   53,  199,
      820,  229,  817,  825,  824,  934,    0,  934,  934,  934,
      281,  285,  934,  934,  934,  934,  934,  934,    0,  934,
      312,    0,    0,  934,    0,  257,  295,  934,  934,  306,
      295,    0,  300,  330,  336,  349,  833,  353,  360,  379,
      369,  934,  811,    0,  818,  828,  823,  824,  807,  194,
      804,  812,  822,  817,  816,  807,  804,  813,  798,  815,

        0,  802,  811,    0,  138,  808,  792,  806,  795,    0,
      788,  803,  802,    0,  794,  803,  799,  792,  780,  781,
      788,  795,  777,  776,    0,  776,  786,  789,  773,  790,
      772,  775,  784,    0,  783,  782,  769,  771,    0,  780,
      771,  934,  317,  384,  934,  934,    0,    0,  390,  266,
      396,  401,  406,  410,  783,  782,  414,  420,  762,  774,
      767,    0,  769,  757,  755,  765,  766,  771,  750,  750,
        0,    0,  751,  754,  762,  754,    0,  745,  759,  745,
      744,  760,  742,  753,  746,  738,  738,    0,  750,  751,
      752,  751,  746,  741,  734,  739,  729,  737,  731,  726,

      733,  720,    0,  711,    0,  718,  726,  710,  715,    0,
      717,  934,  934,  426,  436,  716,  715,    0,    0,    0,
      697,  687,  692,  679,  684,  685,  669,  684,    0,  674,
      674,  665,  656,    0,  661,  668,    0,  668,  621,    0,
      579,  570,  581,  548,  564,  562,  549,  542,  543,  549,
      540,    0,  538,  532,    0,  536,  530,  531,  507,    0,
      523,  410,  402,  401,  416,  415,  398,    0,    0,  398,
      391,  400,  409,    0,  410,  411,    0,  410,    0,    0,
      399,  398,  382,    0,  389,  359,    0,    0,    0,    0,
        0,    0,  349,    0,  348,  327,    0,  334,  331,  311,

        0,    0,    0,    0,  298,  278,  269,  270,  269,    0,
        0,  258,  237,    0,  255,    0,    0,  214,    0,    0,
        0,  202,  196,  191,  183,  167,    0,  158,  109,   73,
       63,    0,    0,    0,    0,   28,    0,    0,    0,  934,
      475,  497,  519,  541,  557,  577,  598,  619,  641,  663,
      685,  701,  713,  730,  752,  767,  781
    } ;

static const flex_int16_t yy_def[458] =
    {   0,
      440,    1,  441,  441,  442,  442,  443,  443,  444,  444,
      440,  440,  440,  440,  440,  445,  440,  440,  440,  440,
      440,  440,  440,  440,  440,  440,  440,  440,  440,  440,
      440,  440,  440,  440,  440,  440,  440,  440,  440,  445,
      445,  445,  445,  445,  445,  445,  445,  445,  445,  445,
      445,  445,  445,  445,  445,  445,  445,  445,  445,  440,
      440,  440,  440,  446,  446,  440,  440,  447,  447,  440,
      448,   67,  440,  449,  450,  440,  440,  445,  440,  440,
      440,  440,  440,  440,  440,  440,  440,  451,  440,  440,
      440,  440,  452,  440,  440,  440,  440,  440,  445,  445,

      445,  445,  445,  445,  445,  445,  445,  445,  445,  445,
      445,  445,  445,  445,  445,  445,  445,  445,  445,  445,
      445,  445,  445,  445,  445,  445,  445,  445,  445,  445,
      445,  445,  445,  445,  445,  445,  445,  445,  445,  445,
      445,  445,  445,  445,  445,  440,  446,  440,  440,  440,
      453,  440,  440,  440,  440,  440,  440,  440,  454,  440,
      455,  447,  448,  440,  449,  450,  450,  440,  440,  440,
      440,  451,  440,  440,  440,  440,  456,  440,  440,  440,
      440,  440,  445,  445,  445,  445,  445,  445,  445,  445,
      445,  445,  445,  445,  445,  445,  445,  445,  445,  445,

      445,  445,  445,  445,  445,  445,  445,  445,  445,  445,
      445,  445,  445,  445,  445,  445,  445,  445,  445,  445,
      445,  445,  445,  445,  445,  445,  445,  445,  445,  445,
      445,  445,  445,  445,  445,  445,  445,  445,  445,  445,
      445,  440,  440,  440,  440,  440,  457,  457,  440,  440,
      440,  440,  440,  440,  456,  456,  440,  440,  445,  445,
      445,  445,  445,  445,  445,  445,  445,  445,  445,  445,
      445,  445,  445,  445,  445,  445,  445,  445,  445,  445,
      445,  445,  445,  445,  445,  445,  445,  445,  445,  445,
      445,  445,  445,  445,  445,  445,  445,  445,  445,  445,

      445,  445,  445,  445,  445,  445,  445,  445,  445,  445,
      445,  440,  440,  440,  440,  445,  445,  445,  445,  445,
      445,  445,  445,  445,  445,  445,  445,  445,  445,  445,
      445,  445,  445,  445,  445,  445,  445,  445,  445,  445,
      445,  445,  445,  445,  445,  445,  445,  445,  445,  445,
      445,  445,  445,  445,  445,  445,  445,  445,  445,  445,
      445,  445,  445,  445,  445,  445,  445,  445,  445,  445,
      445,  445,  445,  445,  445,  445,  445,  445,  445,  445,
      445,  445,  445,  445,  445,  445,  445,  445,  445,  445,
      445,  445,  445,  445,  445,  445,  445,  445,  445,  445,

      445,  445,  445,  445,  445,  445,  445,  445,  445,  445,
      445,  445,  445,  445,  445,  445,  445,  445,  445,  445,
      445,  445,  445,  445,  445,  445,  445,  445,  445,  445,
      445,  445,  445,  445,  445,  445,  445,  445,  445,    0,
      440,  440,  440,  440,  440,  440,  440,  440,  440,  440,
      440,  440,  440,  440,  440,  440,  440
    } ;

static const flex_int16_t yy_nxt[1014] =
    {   0,
       12,   12,   13,   13,   13,   14,   15,   16,   17,   18,
       19,   20,   21,   22,   23,   24,   25,   26,   27,   28,
       29,   29,   29,   29,   30,   31,   32,   33,   34,   35,
       16,   16,   16,   16,   16,   16,   16,   16,   16,   16,
       16,   16,   16,   16,   36,   12,   37,   38,   16,   39,
       40,   41,   42,   43,   44,   45,   46,   16,   47,   16,
       48,   49,   50,   51,   52,   53,   16,   54,   55,   56,
       57,   58,   59,   16,   16,   60,   61,   62,   63,   65,
       72,   72,   66,   82,   73,   73,   84,  102,   65,  107,
      103,   66,   76,   76,   76,  439,   83,   85,  104,  108,

       69,   86,   86,   86,   86,   86,   12,   70,   87,  105,
       12,  231,  106,   88,   12,   12,   12,   12,  438,   12,
      232,   67,   89,   12,   12,   12,   12,   12,  173,  173,
       67,   12,  109,   12,  110,   12,  143,   12,   12,  125,
       69,  437,   67,  126,  111,   12,   90,   70,  128,   91,
      144,   12,  129,   12,  187,  188,   92,  197,   93,  127,
       12,  198,   12,  130,   99,  167,   90,   12,  222,   91,
      168,   12,   12,  436,   12,   12,  100,   12,   12,   92,
      131,  101,   67,  132,  223,   12,  112,  224,   93,   94,
       94,   94,   94,   94,  113,  213,  214,  118,  139,  279,

      114,  134,  280,  115,  119,  120,  116,  219,  140,  226,
      121,  435,   12,  220,   12,  141,  135,  136,   95,  137,
      434,  138,  148,  148,  148,  206,  227,  149,   76,   76,
       76,  150,  170,  170,  170,  170,  170,  433,  207,  208,
      151,  152,  152,  152,  148,  432,  174,   91,  174,  215,
      216,  175,  175,  175,  175,  175,  176,  176,  176,  176,
      431,  171,  265,  266,  191,  192,  153,   91,  193,  233,
      440,  430,  154,  234,  194,  440,  155,   94,   94,   94,
       94,   94,  236,  429,  156,  249,  249,  237,  157,  238,
      158,  159,  160,  178,  161,  179,  179,  179,  179,  179,

      243,  243,  243,  243,  244,  244,  244,  244,  167,  428,
      180,  427,  426,  168,  170,  170,  170,  170,  170,  249,
      249,  425,  424,  423,  181,  170,  170,  170,  170,  170,
      180,  247,  247,  247,  247,  247,  312,  312,  312,  312,
       91,  422,  247,  247,  247,  248,  248,  247,  250,  175,
      175,  175,  175,  175,  171,  251,  251,  251,  251,  251,
       91,  421,  247,  247,  247,  247,  247,  247,  253,  253,
      253,  253,   86,   86,   86,   86,   86,  178,  420,  179,
      179,  179,  179,  179,  252,  419,  418,  180,  179,  179,
      179,  179,  179,  257,  180,  257,  417,  254,  258,  258,

      258,  258,  258,  312,  312,  312,  312,  180,  181,  249,
      249,  416,  415,  414,  180,  251,  251,  251,  251,  251,
      251,  251,  251,  251,  251,  253,  253,  253,  253,  253,
      253,  253,  253,  258,  258,  258,  258,  258,  250,  314,
      314,  314,  314,  314,  252,  314,  314,  314,  314,  314,
      413,  412,  411,  410,  254,  314,  314,  314,  314,  314,
      409,  408,  407,  406,  405,  404,  403,  402,  315,  401,
      400,  399,  398,  397,  315,   64,   64,   64,   64,   64,
       64,   64,   64,   64,   64,   64,   64,   64,   64,   64,
       64,   64,   64,   64,   64,   64,   64,   68,   68,   68,

       68,   68,   68,   68,   68,   68,   68,   68,   68,   68,
       68,   68,   68,   68,   68,   68,   68,   68,   68,   71,
       71,   71,   71,   71,   71,   71,   71,   71,   71,   71,
       71,   71,   71,   71,   71,   71,   71,   71,   71,   71,
       71,   74,   74,   74,   74,   74,   74,   74,   74,   74,
       74,   74,   74,   74,   74,   74,   74,   74,   74,   74,
       74,   74,   74,   78,   78,   78,   78,   78,   78,   78,
       78,   78,   78,   78,   78,  396,   78,  147,  147,  395,
      147,  147,  147,  147,  147,  394,  147,  147,  393,  147,
      147,  392,  147,  391,  147,  390,  389,  147,  162,  162,

      162,  388,  162,  162,  162,  162,  387,  162,  162,  386,
      162,  162,  385,  162,  384,  162,  383,  382,  162,  163,
      163,  163,  163,  163,  163,  163,  163,  163,  163,  163,
      163,  163,  163,  163,  163,  163,  163,  381,  163,  380,
      163,  165,  165,  165,  165,  165,  379,  165,  165,  165,
      165,  165,  165,  165,  165,  165,  165,  165,  165,  165,
      165,  165,  165,  166,  166,  166,  166,  166,  166,  166,
      166,  166,  166,  166,  166,  166,  166,  166,  166,  166,
      166,  166,  166,  166,  166,  172,  378,  172,  172,  172,
      172,  172,  172,  172,  172,  172,  172,  172,  172,  172,

      172,  172,  172,  172,  172,  172,  172,  177,  177,  177,
      177,  177,  177,  242,  242,  242,  242,  242,  242,  242,
      242,  242,  377,  376,  375,  374,  242,  373,  242,  242,
      242,  242,  372,  242,  245,  371,  245,  370,  369,  368,
      245,  245,  245,  245,  245,  367,  366,  245,  365,  245,
      364,  245,  246,  246,  246,  246,  246,  246,  246,  246,
      246,  246,  246,  246,  363,  362,  361,  246,  246,  246,
      246,  360,  246,  255,  255,  255,  255,  255,  255,  359,
      358,  357,  356,  355,  354,  353,  255,  313,  313,  313,
      313,  313,  313,  352,  351,  350,  349,  348,  347,  346,

      345,  344,  343,  342,  341,  340,  339,  338,  337,  336,
      335,  334,  333,  332,  331,  330,  329,  328,  327,  326,
      325,  324,  323,  322,  321,  320,  319,  318,  317,  316,
      440,  256,  311,  310,  309,  308,  307,  306,  305,  304,
      303,  302,  301,  300,  299,  298,  297,  296,  295,  294,
      293,  292,  291,  290,  289,  288,  287,  286,  285,  284,
      283,  282,  281,  278,  277,  276,  275,  274,  273,  272,
      271,  270,  269,  268,  267,  264,  263,  262,  261,  260,
      259,  256,  241,  240,  239,  235,  230,  229,  228,  225,
      221,  218,  217,  212,  211,  210,  209,  205,  204,  203,

      202,  201,  200,  199,  196,  195,  190,  189,  186,  185,
      184,  183,  182,  169,  164,  146,  145,  142,  133,  124,
      123,  122,  117,   98,   97,   96,   81,   80,   79,   77,
      440,   75,   75,   11,  440,  440,  440,  440,  440,  440,
      440,  440,  440,  440,  440,  440,  440,  440,  440,  440,
      440,  440,  440,  440,  440,  440,  440,  440,  440,  440,
      440,  440,  440,  440,  440,  440,  440,  440,  440,  440,
      440,  440,  440,  440,  440,  440,  440,  440,  440,  440,
      440,  440,  440,  440,  440,  440,  440,  440,  440,  440,
      440,  440,  440,  440,  440,  440,  440,  440,  440,  440,

      440,  440,  440,  440,  440,  440,  440,  440,  440,  440,
      440,  440,  440
    } ;

static const flex_int16_t yy_chk[1014] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    3,
        7,    8,    3,   23,    7,    8,   25,   41,    4,   43,
       41,    4,   13,   13,   13,  436,   23,   25,   42,   43,

        5,   26,   26,   26,   26,   26,    3,    5,   27,   42,
        3,  139,   42,   27,    3,    4,    3,    3,  431,    4,
      139,    3,   27,    4,    3,    4,    4,    5,   90,   90,
        4,    5,   44,    4,   44,    5,   58,    5,    5,   51,
        6,  430,    5,   51,   44,    5,   28,    6,   52,   28,
       58,    3,   52,    3,  104,  104,   28,  111,   28,   51,
        4,  111,    4,   53,   40,   75,   28,    6,  133,   28,
       75,    6,    5,  429,    5,    6,   40,    6,    6,   28,
       53,   40,    6,   53,  133,    6,   45,  133,   28,   29,
       29,   29,   29,   29,   45,  126,  126,   47,   56,  205,

       45,   55,  205,   45,   47,   47,   45,  131,   56,  135,
       47,  428,    6,  131,    6,   56,   55,   55,   29,   55,
      426,   55,   67,   67,   67,  120,  135,   67,   76,   76,
       76,   67,   86,   86,   86,   86,   86,  425,  120,  120,
       67,   67,   67,   67,   67,  424,   91,   86,   91,  127,
      127,   91,   91,   91,   91,   91,   92,   92,   92,   92,
      423,   86,  190,  190,  107,  107,   67,   86,  107,  140,
      166,  422,   67,  140,  107,  166,   67,   95,   95,   95,
       95,   95,  142,  418,   67,  250,  250,  142,   67,  142,
       67,   67,   67,   94,   67,   94,   94,   94,   94,   94,

      151,  151,  151,  151,  152,  152,  152,  152,  167,  415,
       94,  413,  412,  167,  171,  171,  171,  171,  171,  173,
      173,  409,  408,  407,   94,  170,  170,  170,  170,  170,
       94,  161,  161,  161,  161,  161,  243,  243,  243,  243,
      170,  406,  161,  161,  161,  161,  161,  161,  173,  174,
      174,  174,  174,  174,  170,  175,  175,  175,  175,  175,
      170,  405,  161,  161,  161,  161,  161,  161,  176,  176,
      176,  176,  178,  178,  178,  178,  178,  179,  400,  179,
      179,  179,  179,  179,  175,  399,  398,  178,  181,  181,
      181,  181,  181,  180,  179,  180,  396,  176,  180,  180,

      180,  180,  180,  244,  244,  244,  244,  178,  179,  249,
      249,  395,  393,  386,  179,  251,  251,  251,  251,  251,
      252,  252,  252,  252,  252,  253,  253,  253,  253,  254,
      254,  254,  254,  257,  257,  257,  257,  257,  249,  258,
      258,  258,  258,  258,  251,  314,  314,  314,  314,  314,
      385,  383,  382,  381,  253,  315,  315,  315,  315,  315,
      378,  376,  375,  373,  372,  371,  370,  367,  258,  366,
      365,  364,  363,  362,  314,  441,  441,  441,  441,  441,
      441,  441,  441,  441,  441,  441,  441,  441,  441,  441,
      441,  441,  441,  441,  441,  441,  441,  442,  442,  442,

      442,  442,  442,  442,  442,  442,  442,  442,  442,  442,
      442,  442,  442,  442,  442,  442,  442,  442,  442,  443,
      443,  443,  443,  443,  443,  443,  443,  443,  443,  443,
      443,  443,  443,  443,  443,  443,  443,  443,  443,  443,
      443,  444,  444,  444,  444,  444,  444,  444,  444,  444,
      444,  444,  444,  444,  444,  444,  444,  444,  444,  444,
      444,  444,  444,  445,  445,  445,  445,  445,  445,  445,
      445,  445,  445,  445,  445,  361,  445,  446,  446,  359,
      446,  446,  446,  446,  446,  358,  446,  446,  357,  446,
      446,  356,  446,  354,  446,  353,  351,  446,  447,  447,

      447,  350,  447,  447,  447,  447,  349,  447,  447,  348,
      447,  447,  347,  447,  346,  447,  345,  344,  447,  448,
      448,  448,  448,  448,  448,  448,  448,  448,  448,  448,
      448,  448,  448,  448,  448,  448,  448,  343,  448,  342,
      448,  449,  449,  449,  449,  449,  341,  449,  449,  449,
      449,  449,  449,  449,  449,  449,  449,  449,  449,  449,
      449,  449,  449,  450,  450,  450,  450,  450,  450,  450,
      450,  450,  450,  450,  450,  450,  450,  450,  450,  450,
      450,  450,  450,  450,  450,  451,  339,  451,  451,  451,
      451,  451,  451,  451,  451,  451,  451,  451,  451,  451,

      451,  451,  451,  451,  451,  451,  451,  452,  452,  452,
      452,  452,  452,  453,  453,  453,  453,  453,  453,  453,
      453,  453,  338,  336,  335,  333,  453,  332,  453,  453,
      453,  453,  331,  453,  454,  330,  454,  328,  327,  326,
      454,  454,  454,  454,  454,  325,  324,  454,  323,  454,
      322,  454,  455,  455,  455,  455,  455,  455,  455,  455,
      455,  455,  455,  455,  321,  317,  316,  455,  455,  455,
      455,  311,  455,  456,  456,  456,  456,  456,  456,  309,
      308,  307,  306,  304,  302,  301,  456,  457,  457,  457,
      457,  457,  457,  300,  299,  298,  297,  296,  295,  294,

      293,  292,  291,  290,  289,  287,  286,  285,  284,  283,
      282,  281,  280,  279,  278,  276,  275,  274,  273,  270,
      269,  268,  267,  266,  265,  264,  263,  261,  260,  259,
      256,  255,  241,  240,  238,  237,  236,  235,  233,  232,
      231,  230,  229,  228,  227,  226,  224,  223,  222,  221,
      220,  219,  218,  217,  216,  215,  213,  212,  211,  209,
      208,  207,  206,  203,  202,  200,  199,  198,  197,  196,
      195,  194,  193,  192,  191,  189,  188,  187,  186,  185,
      183,  177,  145,  144,  143,  141,  138,  137,  136,  134,
      132,  130,  128,  125,  124,  123,  122,  119,  117,  116,

      115,  114,  113,  112,  110,  109,  106,  105,  103,  102,
      100,   99,   97,   77,   72,   61,   59,   57,   54,   50,
       49,   48,   46,   34,   33,   32,   22,   18,   17,   14,
       11,   10,    9,  440,  440,  440,  440,  440,  440,  440,
      440,  440,  440,  440,  440,  440,  440,  440,  440,  440,
      440,  440,  440,  440,  440,  440,  440,  440,  440,  440,
      440,  440,  440,  440,  440,  440,  440,  440,  440,  440,
      440,  440,  440,  440,  440,  440,  440,  440,  440,  440,
      440,  440,  440,  440,  440,  440,  440,  440,  440,  440,
      440,  440,  440,  440,  440,  440,  440,  440,  440,  440,

      440,  440,  440,  440,  440,  440,  440,  440,  440,  440,
      440,  440,  440
    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[150] =
    {   0,
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 1, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
#ifndef YYLMAX
#define YYLMAX 8192
#endif

char yytext[YYLMAX];
char *yytext_ptr;
#line 1 "lexer.l"
#line 6 "lexer.l"

#include <string>
#include <algorithm>
#include <charconv>
#include <iostream>
#include <cstdio>


void Print(const std::string& message)
{
    std::cout << message << std::endl;
}

void PrintError(const std::string& errorMessage, const int line = -1) 
{
    std::cerr << "error: " << errorMessage << std::endl;
    if (line >= 0)
        std::cerr << "error line: " << line << std::endl;
    std::cerr << std::endl;
}

void PrintIntegerLiteral(const std::string& type, const int integer) {
    Print("Found " + type + " integer literal: " + std::to_string(integer));
}

void PrintFloatingPointLiteral(const double floatingPoint) {
    Print("Found floating point literal: " + std::to_string(floatingPoint));
}

void PrintStringLiteral(const std::string& literal) {
    Print("Found string literal: \"" + literal + "\"");
}

void RemoveCharacterFromString(std::string& str, char ch) {
    const auto newLast = std::remove(str.begin(), str.end(), ch);
    str.erase(newLast, str.end());
}

void RemoveUnderline(std::string& str) {
    RemoveCharacterFromString(str, '_');
}

#line 897 "lexer.flex.cpp"

#line 899 "lexer.flex.cpp"

#define INITIAL 0
#define DOUBLE_STR 1
#define SINGLE_STR 2
#define TEMPLATE_STR 3
#define MULTILINE_COMMENT 4

/*windows compatibility case*/
#include <io.h>
#define isatty _isatty
#define fileno _fileno
    
#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 79 "lexer.l"




#line 84 "lexer.l"
std::string currentString;
std::string currentComment;
int currentInteger;
char currentCharacter;
double currentFloatingPoint;
char buffer[10];    



#line 1132 "lexer.flex.cpp"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 441 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_current_state != 440 );
		yy_cp = (yy_last_accepting_cpos);
		yy_current_state = (yy_last_accepting_state);

yy_find_action:
		yy_act = yy_accept[yy_current_state];

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 93 "lexer.l"
{ Print("Found KW_ABSTRACT: " + std::string{yytext}); } 
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 94 "lexer.l"
{ Print("Found TYPE_ANY: " + std::string{yytext}); } 
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 95 "lexer.l"
{ Print("Found KW_AS: " + std::string{yytext}); } 
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 96 "lexer.l"
{ Print("Found TYPE_BOOLEAN: " + std::string{yytext}); } 
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 97 "lexer.l"
{ Print("Found KW_BREAK: " + std::string{yytext}); } 
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 98 "lexer.l"
{ Print("Found KW_CASE: " + std::string{yytext}); } 
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 99 "lexer.l"
{ Print("Found KW_CATCH: " + std::string{yytext}); } 
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 100 "lexer.l"
{ Print("Found KW_CLASS: " + std::string{yytext}); } 
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 101 "lexer.l"
{ Print("Found KW_CONTINUE: " + std::string{yytext}); } 
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 102 "lexer.l"
{ Print("Found KW_CONST: " + std::string{yytext}); } 
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 103 "lexer.l"
{ Print("Found KW_CONSTRUCTOR: " + std::string{yytext}); } 
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 104 "lexer.l"
{ Print("Found KW_DEBUGGER: " + std::string{yytext}); } 
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 105 "lexer.l"
{ Print("Found KW_DECLARE: " + std::string{yytext}); } 
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 106 "lexer.l"
{ Print("Found KW_DEFAULT: " + std::string{yytext}); } 
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 107 "lexer.l"
{ Print("Found KW_DELETE: " + std::string{yytext}); } 
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 108 "lexer.l"
{ Print("Found KW_DO: " + std::string{yytext}); } 
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 109 "lexer.l"
{ Print("Found KW_ELSE: " + std::string{yytext}); } 
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 110 "lexer.l"
{ Print("Found KW_ENUM: " + std::string{yytext}); } 
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 111 "lexer.l"
{ Print("Found KW_EXPORT: " + std::string{yytext}); } 
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 112 "lexer.l"
{ Print("Found KW_EXTENDS: " + std::string{yytext}); } 
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 113 "lexer.l"
{ Print("Found KW_FALSE: " + std::string{yytext}); } 
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 114 "lexer.l"
{ Print("Found KW_FINALLY: " + std::string{yytext}); } 
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 115 "lexer.l"
{ Print("Found KW_FOR: " + std::string{yytext}); } 
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 116 "lexer.l"
{ Print("Found KW_FROM: " + std::string{yytext}); } 
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 117 "lexer.l"
{ Print("Found KW_FUNCTION: " + std::string{yytext}); } 
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 118 "lexer.l"
{ Print("Found KW_GET: " + std::string{yytext}); } 
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 119 "lexer.l"
{ Print("Found KW_IF: " + std::string{yytext}); } 
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 120 "lexer.l"
{ Print("Found KW_IMPLEMENTS: " + std::string{yytext}); } 
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 121 "lexer.l"
{ Print("Found KW_IMPORT: " + std::string{yytext}); } 
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 122 "lexer.l"
{ Print("Found KW_IN: " + std::string{yytext}); } 
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 123 "lexer.l"
{ Print("Found KW_INFER: " + std::string{yytext}); } 
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 124 "lexer.l"
{ Print("Found KW_INSTANCEOF: " + std::string{yytext}); } 
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 125 "lexer.l"
{ Print("Found KW_INTARFACE: " + std::string{yytext}); } 
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 126 "lexer.l"
{ Print("Found KW_IS: " + std::string{yytext}); } 
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 127 "lexer.l"
{ Print("Found KW_KEYOF: " + std::string{yytext}); } 
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 128 "lexer.l"
{ Print("Found KW_LET: " + std::string{yytext}); } 
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 129 "lexer.l"
{ Print("Found KW_MODULE: " + std::string{yytext}); } 
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 130 "lexer.l"
{ Print("Found KW_NAMESPACE: " + std::string{yytext}); } 
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 131 "lexer.l"
{ Print("Found TYPE_NEVER: " + std::string{yytext}); } 
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 132 "lexer.l"
{ Print("Found KW_NEW: " + std::string{yytext}); } 
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 133 "lexer.l"
{ Print("Found KW_NULL: " + std::string{yytext}); } 
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 134 "lexer.l"
{ Print("Found TYPE_NUMBER: " + std::string{yytext}); } 
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 135 "lexer.l"
{ Print("Found TYPE_OBJECT: " + std::string{yytext}); } 
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 136 "lexer.l"
{ Print("Found KW_OF: " + std::string{yytext}); } 
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 137 "lexer.l"
{ Print("Found KW_PACKAGE: " + std::string{yytext}); } 
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 138 "lexer.l"
{ Print("Found KW_PRIVATE: " + std::string{yytext}); } 
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 139 "lexer.l"
{ Print("Found KW_PROTECTED: " + std::string{yytext}); } 
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 140 "lexer.l"
{ Print("Found KW_PUBLIC: " + std::string{yytext}); } 
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 141 "lexer.l"
{ Print("Found KW_READONLY: " + std::string{yytext}); } 
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 142 "lexer.l"
{ Print("Found KW_REQUIRE: " + std::string{yytext}); } 
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 143 "lexer.l"
{ Print("Found KW_RETURN: " + std::string{yytext}); } 
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 144 "lexer.l"
{ Print("Found KW_SET: " + std::string{yytext}); } 
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 145 "lexer.l"
{ Print("Found KW_STATIC: " + std::string{yytext}); } 
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 146 "lexer.l"
{ Print("Found TYPE_STRING: " + std::string{yytext}); } 
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 147 "lexer.l"
{ Print("Found KW_SUPER: " + std::string{yytext}); } 
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 148 "lexer.l"
{ Print("Found KW_SWITCH: " + std::string{yytext}); }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 149 "lexer.l"
{ Print("Found TYPE_SYMBOL: " + std::string{yytext}); }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 150 "lexer.l"
{ Print("Found KW_THIS: " + std::string{yytext}); }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 151 "lexer.l"
{ Print("Found KW_THROW: " + std::string{yytext}); }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 152 "lexer.l"
{ Print("Found KW_TRUE: " + std::string{yytext}); }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 153 "lexer.l"
{ Print("Found KW_TRY: " + std::string{yytext}); }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 154 "lexer.l"
{ Print("Found KW_TYPE: " + std::string{yytext}); }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 155 "lexer.l"
{ Print("Found KW_TYPEOF: " + std::string{yytext}); }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 156 "lexer.l"
{ Print("Found KW_UNDEFINED: " + std::string{yytext}); }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 157 "lexer.l"
{ Print("Found KW_UNIQUE: " + std::string{yytext}); } 
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 158 "lexer.l"
{ Print("Found TYPE_UNKNOWN: " + std::string{yytext}); } 
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 159 "lexer.l"
{ Print("Found KW_VAR: " + std::string{yytext}); }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 160 "lexer.l"
{ Print("Found VOID_OPERATOR: " + std::string{yytext}); }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 161 "lexer.l"
{ Print("Found KW_WHILE: " + std::string{yytext}); }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 163 "lexer.l"
{ Print("Found OPERATOR_OPT_PARAM: " + std::string{yytext}); }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 164 "lexer.l"
{ Print("Found OPERATOR_MOD: " + std::string{yytext}); }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 165 "lexer.l"
{ Print("Found OPERATOR_MOD_ASSIGNMENT: " + std::string{yytext}); }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 166 "lexer.l"
{ Print("Found OPERATOR_PLUS: " + std::string{yytext}); }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 167 "lexer.l"
{ Print("Found OPERATOR_PLUS_ASSIGNMENT: " + std::string{yytext}); }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 168 "lexer.l"
{ Print("Found OPERATOR_INCREMENT: " + std::string{yytext}); }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 169 "lexer.l"
{ Print("Found OPERATOR_MINUS: " + std::string{yytext}); }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 170 "lexer.l"
{ Print("Found OPERATOR_MINUS_ASSIGNMENT: " + std::string{yytext}); }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 171 "lexer.l"
{ Print("Found OPERATOR_DICREMENT: " + std::string{yytext}); }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 172 "lexer.l"
{ Print("Found OPERATOR_MUL: " + std::string{yytext}); }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 173 "lexer.l"
{ Print("Found OPERATOR_MUL_ASSIGNMENT: " + std::string{yytext}); }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 174 "lexer.l"
{ Print("Found OPERATOR_ASSIGNMENT: " + std::string{yytext}); }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 175 "lexer.l"
{ Print("Found OPERATOR_EQUAL: " + std::string{yytext}); }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 176 "lexer.l"
{ Print("Found OPERATOR_EQUAL_BY_TYPE_AND_VALUE: " + std::string{yytext}); }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 177 "lexer.l"
{ Print("Found OPERATOR_BIT_NOT: " + std::string{yytext}); }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 178 "lexer.l"
{ Print("Found OPERATOR_NOT_EQUAL: " + std::string{yytext}); }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 179 "lexer.l"
{ Print("Found OPERATOR_NOT_EQUAL_BY_TYPE_AND_VALUE: " + std::string{yytext}); }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 180 "lexer.l"
{ Print("Found OPERATOR_MORE: " + std::string{yytext}); }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 181 "lexer.l"
{ Print("Found OPERATOR_MORE_OR_EQUAL: " + std::string{yytext}); }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 182 "lexer.l"
{ Print("Found OPERATOR_LESS: " + std::string{yytext}); }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 183 "lexer.l"
{ Print("Found OPERATOR_LESS_OR_EQUA: " + std::string{yytext}); }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 184 "lexer.l"
{ Print("Found OPERATOR_DIV: " + std::string{yytext}); }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 185 "lexer.l"
{ Print("Found OPERATOR_DIV_ASSIGNMENT: " + std::string{yytext}); }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 186 "lexer.l"
{ Print("Found OPERATOR_BIT_XOR: " + std::string{yytext}); }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 187 "lexer.l"
{ Print("Found UNARY_BITWISE_NOT: " + std::string{yytext}); }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 188 "lexer.l"
{ Print("Found OPERATOR_AMPERSAND: " + std::string{yytext}); }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 189 "lexer.l"
{ Print("Found OPERATOR_AND: " + std::string{yytext}); }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 190 "lexer.l"
{ Print("Found OPERATOR_BIT_OR: " + std::string{yytext}); }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 191 "lexer.l"
{ Print("Found OPERATOR_OR: " + std::string{yytext}); }
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 192 "lexer.l"
{ Print("Found LEFT_SQUARE_BRACKET: " + std::string{yytext}); }
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 193 "lexer.l"
{ Print("Found RIGHT_SQUARE_BRACKET: " + std::string{yytext}); }
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 194 "lexer.l"
{ Print("Found LEFT_ROUND_BRACKET: " + std::string{yytext}); }
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 195 "lexer.l"
{ Print("Found RIGHT_ROUND_BRACKET: " + std::string{yytext}); }
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 196 "lexer.l"
{ Print("Found LEFT_FIGURE_BRACKET: " + std::string{yytext}); }
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 197 "lexer.l"
{ Print("Found RIGHT_FIGURE_BRACKET: " + std::string{yytext}); }
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 198 "lexer.l"
{ Print("Found COLON: " + std::string{yytext}); }
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 199 "lexer.l"
{ Print("Found COMMA: " + std::string{yytext}); }
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 200 "lexer.l"
{ Print("Found DOT: " + std::string{yytext}); }
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 201 "lexer.l"
{ Print("Found SEMICOLON: " + std::string{yytext}); }
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 202 "lexer.l"
{ Print("Found OPERATOR_ENTER: \\n" + std::string{yytext}); }
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 204 "lexer.l"
{
    currentString.clear();
    BEGIN(DOUBLE_STR);
}
	YY_BREAK
case 111:
/* rule 111 can match eol */
YY_RULE_SETUP
#line 208 "lexer.l"
{
    currentString += yytext;
}
	YY_BREAK
case 112:
/* rule 112 can match eol */
YY_RULE_SETUP
#line 211 "lexer.l"
{
    PrintError("invalid hexadecimal escape sequence", yylineno);
}
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 214 "lexer.l"
{
    std::fill(std::begin(buffer), std::end(buffer), 0);
    std::copy(yytext, yytext + yyleng, buffer);
    std::sscanf(buffer + 2, "%x", &currentInteger);
    currentString += static_cast<char>(currentInteger);
}
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 220 "lexer.l"
{
    PrintError("octal escape sequence are not allowed", yylineno);
}
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 223 "lexer.l"
{
    PrintError("unicode escape sequence is not supported yet", yylineno);
}
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 226 "lexer.l"
{
    currentString += "\'";
}
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 229 "lexer.l"
{
    currentString += "\"";
}
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 232 "lexer.l"
{
    currentString += "\\";
}
	YY_BREAK
case 119:
YY_RULE_SETUP
#line 235 "lexer.l"
{
    currentString += "\b";
}
	YY_BREAK
case 120:
YY_RULE_SETUP
#line 238 "lexer.l"
{
    currentString += "\f";
}
	YY_BREAK
case 121:
YY_RULE_SETUP
#line 241 "lexer.l"
{
    currentString += "\n";
}
	YY_BREAK
case 122:
YY_RULE_SETUP
#line 244 "lexer.l"
{
    currentString += "\r";
}
	YY_BREAK
case 123:
YY_RULE_SETUP
#line 247 "lexer.l"
{
    currentString += "\t";
}
	YY_BREAK
case 124:
YY_RULE_SETUP
#line 250 "lexer.l"
{
    currentString += "\v";
}
	YY_BREAK
case 125:
/* rule 125 can match eol */
YY_RULE_SETUP
#line 253 "lexer.l"
{
    currentString += "\0";
}
	YY_BREAK
case 126:
/* rule 126 can match eol */
YY_RULE_SETUP
#line 256 "lexer.l"
{
    PrintError("invalid escape character", yylineno);
}
	YY_BREAK
case 127:
/* rule 127 can match eol */
YY_RULE_SETUP
#line 259 "lexer.l"
{
    PrintError("expected end of string literal but found end of line!", yylineno);
    BEGIN(INITIAL);
}
	YY_BREAK
case YY_STATE_EOF(DOUBLE_STR):
case YY_STATE_EOF(SINGLE_STR):
case YY_STATE_EOF(TEMPLATE_STR):
#line 263 "lexer.l"
{
    PrintError("expected end of string literal but found end of file!", yylineno);
    BEGIN(INITIAL);
}
	YY_BREAK
case 128:
YY_RULE_SETUP
#line 267 "lexer.l"
{
    PrintStringLiteral(currentString);
    BEGIN(INITIAL);
}
	YY_BREAK
case 129:
YY_RULE_SETUP
#line 272 "lexer.l"
{
    currentString.clear();
    BEGIN(SINGLE_STR);
}
	YY_BREAK
case 130:
/* rule 130 can match eol */
YY_RULE_SETUP
#line 276 "lexer.l"
{
    currentString += yytext;
}
	YY_BREAK
case 131:
YY_RULE_SETUP
#line 279 "lexer.l"
{
    PrintStringLiteral(currentString);
    BEGIN(INITIAL);
}
	YY_BREAK
case 132:
YY_RULE_SETUP
#line 284 "lexer.l"
{
    currentString.clear();
    BEGIN(TEMPLATE_STR);
}
	YY_BREAK
case 133:
/* rule 133 can match eol */
YY_RULE_SETUP
#line 288 "lexer.l"
{
    currentString += yytext;
}
	YY_BREAK
case 134:
YY_RULE_SETUP
#line 291 "lexer.l"
{
    currentString += "\`";
}
	YY_BREAK
case 135:
YY_RULE_SETUP
#line 294 "lexer.l"
{
    PrintStringLiteral(currentString);
    BEGIN(INITIAL);
}
	YY_BREAK
case 136:
YY_RULE_SETUP
#line 300 "lexer.l"
{
    currentComment.clear();
    BEGIN(MULTILINE_COMMENT);
}
	YY_BREAK
case 137:
/* rule 137 can match eol */
YY_RULE_SETUP
#line 304 "lexer.l"
{
    currentComment += yytext;
}
	YY_BREAK
case 138:
/* rule 138 can match eol */
YY_RULE_SETUP
#line 307 "lexer.l"
{
    currentComment += yytext;
}
	YY_BREAK
case 139:
YY_RULE_SETUP
#line 310 "lexer.l"
{
    Print("Found multiline comment: \n" + currentComment);
    BEGIN(INITIAL);
}
	YY_BREAK
case YY_STATE_EOF(MULTILINE_COMMENT):
#line 314 "lexer.l"
{
    PrintError("no closing */ of multiline comment", yylineno);
    BEGIN(INITIAL);
}
	YY_BREAK
case 140:
YY_RULE_SETUP
#line 319 "lexer.l"
{ 
    Print("Found singleline comment: " + std::string{yytext + 2}); 
}
	YY_BREAK
case 141:
YY_RULE_SETUP
#line 324 "lexer.l"
{ /* Decimal literal */
    std::string number_string = yytext;
    RemoveCharacterFromString(number_string, '_');
    std::from_chars(number_string.c_str(), number_string.c_str() + number_string.size(), currentFloatingPoint);
    PrintFloatingPointLiteral(currentFloatingPoint);
}
	YY_BREAK
case 142:
YY_RULE_SETUP
#line 331 "lexer.l"
{
    std::string number_string = yytext;
    RemoveCharacterFromString(number_string, '_');
    std::from_chars(number_string.c_str(), number_string.c_str() + number_string.size(), currentFloatingPoint);
    PrintFloatingPointLiteral(currentFloatingPoint);
}
	YY_BREAK
case 143:
YY_RULE_SETUP
#line 338 "lexer.l"
{
    std::string number_string = yytext;
    RemoveCharacterFromString(number_string, '_');
    std::from_chars(number_string.c_str(), number_string.c_str() + number_string.size(), currentInteger);
    PrintIntegerLiteral("decimal", currentInteger); 
}
	YY_BREAK
case 144:
YY_RULE_SETUP
#line 346 "lexer.l"
{ /* Binary integer literal */
    currentInteger = 0;
    std::string number_string = yytext;
    RemoveCharacterFromString(number_string, '_');
    std::from_chars(number_string.c_str() + 2, number_string.c_str() + number_string.size(), currentInteger, 2);
    PrintIntegerLiteral("binary", currentInteger); 
}
	YY_BREAK
case 145:
YY_RULE_SETUP
#line 355 "lexer.l"
{  /* Octal integer literal */
    currentInteger = 0;
    std::string number_string = yytext;
    RemoveCharacterFromString(number_string, '_');
    std::from_chars(number_string.c_str() + 2, number_string.c_str() + number_string.size(), currentInteger, 8);
    PrintIntegerLiteral("octal", currentInteger); 
}
	YY_BREAK
case 146:
YY_RULE_SETUP
#line 364 "lexer.l"
{  /* Hexadecimal integer literal */
    currentInteger = 0;
    std::string number_string = yytext;
    RemoveCharacterFromString(number_string, '_');
    std::from_chars(number_string.c_str() + 2, number_string.c_str() + number_string.size(), currentInteger, 16);
    PrintIntegerLiteral("hexadecimal", currentInteger); 
}
	YY_BREAK
case 147:
YY_RULE_SETUP
#line 373 "lexer.l"
{ Print("Found identifier: " + std::string{yytext}); }
	YY_BREAK
case 148:
/* rule 148 can match eol */
YY_RULE_SETUP
#line 376 "lexer.l"
{ /* ignoring */ }
	YY_BREAK
case 149:
YY_RULE_SETUP
#line 378 "lexer.l"
ECHO;
	YY_BREAK
#line 2073 "lexer.flex.cpp"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_last_accepting_cpos);
				yy_current_state = (yy_last_accepting_state);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 441 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 441 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 440);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 378 "lexer.l"


int main(int argc, char *argv[]) {
    if (argc < 2) {
        Print("Usage: %s <input_file>\n" + std::string{argv[0]});
        return 1;
    }

    FILE *input_file = fopen(argv[1], "r");
    if (!input_file) {
        PrintError("could not open file: " + std::string{argv[1]});
        return 1;
    }
    
	FILE* output_file = fopen("output.txt", "w");
	if (!output_file) {
		PrintError("could not create output file\n");
		fclose(input_file);
		return 1;
	}

    yyin = input_file;
    yyout = output_file;
    yylex();        

	fclose(input_file);
	fclose(output_file);
    return 0;
}

